baseURL = 'https://maplibre.org/'
languageCode = 'en-us'
title = 'MapLibre'

sectionPagesMenu = "main"

copyright = "Creative Commons Zero v1.0 Universal"

enableGitInfo = true
summaryLength = 30
enableEmoji = true

paginate = 50

[taxonomies]
  author = "authors"
  category = "categories"

[menu]

[params]
  description = "Open-source mapping libraries for developers of web and mobile applications."
  keywords = "maplibre maps"
  githubProjectUrl = "https://github.com/maplibre/maplibre.github.io"

# Links format
[permalinks]
  posts = "/posts/:year/:month/:slug/"
  datefmt  = "Jan 2, 2006"

  [markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    tabWidth = 4
    style = 'friendly'
